"""
Discrete Event Simulator (DES) event type hierarchy.

All events carry a nanosecond-precision timestamp and implement __lt__
so they can be inserted directly into Python's heapq min-heap without
a wrapper tuple.

Design principles:
  - Frozen dataclasses: events are immutable once created.
  - Integer timestamps (int64 ns since Unix epoch): avoids float precision
    loss at nanosecond resolution and matches Binance raw trade timestamps.
  - Side represented as a string ('buy'/'sell') for simplicity; the Rust
    core uses an enum internally and converts at the PyO3 boundary.
  - LatencyDelayEvent is a container event: it holds the original inner
    event and re-fires it at timestamp_ns + latency_ns. This is the entire
    slippage mechanism -- any market events processed between the original
    signal and the delayed execution cause organic price movement.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------

@dataclass(frozen=True, order=False)
class BaseEvent:
    """Root of the event hierarchy. Ordered by nanosecond timestamp."""

    timestamp_ns: int   # int64: nanoseconds since Unix epoch (UTC)

    def __lt__(self, other: "BaseEvent") -> bool:
        return self.timestamp_ns < other.timestamp_ns

    def __le__(self, other: "BaseEvent") -> bool:
        return self.timestamp_ns <= other.timestamp_ns

    def __gt__(self, other: "BaseEvent") -> bool:
        return self.timestamp_ns > other.timestamp_ns

    def __ge__(self, other: "BaseEvent") -> bool:
        return self.timestamp_ns >= other.timestamp_ns


# ---------------------------------------------------------------------------
# Market data events  (sourced from Parquet tick data)
# ---------------------------------------------------------------------------

@dataclass(frozen=True, order=False)
class MarketTick(BaseEvent):
    """A single aggressor trade that hit the order book.

    Sourced from Binance Vision 'trades' files.
    Each row is one matched trade: a taker order crossed the spread.

    Fields:
        price:   Execution price (float, original precision from exchange).
        qty:     Quantity traded in base asset (e.g. BTC).
        side:    Aggressor side: 'buy' (taker bought) or 'sell' (taker sold).
        trade_id: Exchange-assigned trade ID for deduplication.
    """
    price: float = 0.0
    qty: float = 0.0
    side: str = "buy"       # 'buy' | 'sell'
    trade_id: int = 0


@dataclass(frozen=True, order=False)
class L2Delta(BaseEvent):
    """An incremental update to a single price level in the order book.

    Sourced from Binance Vision 'depthUpdate' stream snapshots.
    A qty_delta of 0.0 means the price level was fully removed.

    Fields:
        price_level: The absolute price of the affected level.
        qty:         New total quantity at this level (NOT a delta).
                     0.0 = level deleted. Binance uses absolute qty in snapshots.
        side:        'bid' or 'ask'.
        is_snapshot: True on the first event of a full depth snapshot batch.
    """
    price_level: float = 0.0
    qty: float = 0.0
    side: str = "bid"       # 'bid' | 'ask'
    is_snapshot: bool = False


@dataclass(frozen=True, order=False)
class L3OrderAdd(BaseEvent):
    """A new limit order placed in the order book (Level 3 / order-by-order).

    Not available from Binance public data. Used when feeding synthetic
    L3 data or from exchanges that provide MBO (market-by-order) feeds.
    """
    order_id: int = 0
    price: float = 0.0
    qty: float = 0.0
    side: str = "bid"       # 'bid' | 'ask'


@dataclass(frozen=True, order=False)
class L3OrderCancel(BaseEvent):
    """Cancellation of an existing limit order by ID."""
    order_id: int = 0


@dataclass(frozen=True, order=False)
class L3OrderFill(BaseEvent):
    """Partial or full fill of an existing limit order."""
    order_id: int = 0
    fill_qty: float = 0.0
    fill_price: float = 0.0


# ---------------------------------------------------------------------------
# Strategy / execution events  (generated by DES and strategy)
# ---------------------------------------------------------------------------

@dataclass(frozen=True, order=False)
class SignalEvent(BaseEvent):
    """A directional trade signal generated by the strategy.

    When the DES dispatches this event, the InProcessLatencyBridge
    intercepts it and re-schedules a LatencyDelayEvent at:
        timestamp_ns + HFTConfig.latency_ns

    This models the round-trip latency from signal generation to
    the exchange matching engine receiving and processing the order.

    Fields:
        side:       'long' or 'short'.
        price:      Desired limit price (or 0.0 for market order).
        qty:        Desired quantity in base asset.
        order_type: 'limit' | 'market'.
        strategy_id: Identifier for the generating strategy.
    """
    side: str = "long"          # 'long' | 'short'
    price: float = 0.0          # 0.0 = market order
    qty: float = 0.0
    order_type: str = "limit"   # 'limit' | 'market'
    strategy_id: str = "default"


@dataclass(frozen=True, order=False)
class LatencyDelayEvent(BaseEvent):
    """Container event that re-fires an inner event at a future timestamp.

    This is the core of the in-process latency bridge. When the DES pops
    this event, it extracts `inner_event` and dispatches it as if it had
    just arrived, but at `timestamp_ns` (which is `signal_time + latency_ns`).

    Any market events (MarketTick, L2Delta) processed in the interval
    [signal_time, signal_time + latency_ns] will have already updated the
    order book state before the signal's order is submitted, producing
    organic slippage without any artificial slip model.
    """
    inner_event: Optional[BaseEvent] = field(default=None, compare=False)


@dataclass(frozen=True, order=False)
class OrderSubmitEvent(BaseEvent):
    """Order submission to the matching engine (after latency delay fires).

    Created by the DES when it processes a LatencyDelayEvent wrapping a
    SignalEvent. Sent to the LOB for matching.
    """
    order_id: int = 0
    side: str = "bid"           # 'bid' | 'ask' (exchange-facing)
    price: float = 0.0
    qty: float = 0.0
    order_type: str = "limit"
    strategy_id: str = "default"


@dataclass(frozen=True, order=False)
class OrderAckEvent(BaseEvent):
    """Acknowledgement that an order was accepted by the matching engine."""
    order_id: int = 0
    accepted_price: float = 0.0
    accepted_qty: float = 0.0


@dataclass(frozen=True, order=False)
class FillEvent(BaseEvent):
    """A (partial or full) fill of a previously submitted order.

    Generated by the LOB matching engine when a submitted order crosses
    the spread or is resting and gets hit.
    """
    order_id: int = 0
    fill_price: float = 0.0
    fill_qty: float = 0.0
    side: str = "bid"
    is_taker: bool = True       # Taker = crossed spread, Maker = resting


@dataclass(frozen=True, order=False)
class OrderCancelEvent(BaseEvent):
    """Request to cancel an existing resting order."""
    order_id: int = 0


@dataclass(frozen=True, order=False)
class SimEndEvent(BaseEvent):
    """Sentinel event that signals the DES to stop processing.

    Scheduled at the end of the data stream to flush any open positions
    and finalize metrics collection.
    """
    pass
