import pytest
import pandas as pd
from engine.config import StrategyConfig, HFTConfig
from engine.data_loader import BinanceDataLoader
from engine.hft_data_loader import HFTDataLoader
from engine.des_engine import DiscreteEventSimulator
from engine.hft_bar_wrapper import BarToHFTWrapper
from strategies.trend_oscillator import TrendOscillatorStrategy
from hft_engine import PositionStatus


def test_concurrency_sync_trace_validation():
    loader = BinanceDataLoader(cache_dir="data")
    df = loader.fetch_candles("BTCUSDT", "4h", "2023-07-01", "2025-01-01")

    # Initialize strategy and compute indicators
    strategy_config = StrategyConfig(
        starting_capital=10000.0,
        fee_rate=0.0004,
        warmup_candles=200,
    )
    strategy = TrendOscillatorStrategy(strategy_config)
    df_enriched = strategy.compute_indicators(df)

    # Load daily ticks
    hft_loader = HFTDataLoader(cache_dir="data/hft")
    symbol = "BTCUSDT"
    date = "2024-07-01"

    ticks = list(hft_loader.stream_trades(symbol, date))
    assert len(ticks) > 0, "No tick data loaded"

    # Slice first 350,000 ticks to ensure we cross the 4H bar boundary at 04:00:00
    ticks_slice = ticks[:350000]

    hft_config = HFTConfig(
        use_rust_lob=True,
        starting_capital=10000.0,
        latency_ns=50_000,
        fee_rate_taker=0.0004,
        fee_rate_maker=0.0001,
        warmup_events=0,
        max_events=400000,
    )
    des = DiscreteEventSimulator(hft_config)
    wrapper = BarToHFTWrapper(df_enriched, strategy, warmup_candles=200)

    result = des.run(iter(ticks_slice), wrapper)
    assert result is not None

    # Retrieve and validate the trace logs generated by the Rust TraceLogger
    events = des.trace_logger.get_events()
    assert len(events) > 0, "No trace events recorded by Rust TraceLogger"

    print("\nRecorded Trace Events:")
    for e in events:
        print(
            f"[{e.timestamp_ns}] Thread {e.thread_id} | {e.event_type} | {e.metadata}"
        )

    # Assertions on event ordering
    sync_starts = [e for e in events if e.event_type == "BoundarySyncStart"]
    sync_ends = [e for e in events if e.event_type == "BoundarySyncEnd"]
    state_updates = [e for e in events if e.event_type == "StateBrokerUpdate"]

    # Verify boundary gatekeeper transitions
    assert len(sync_starts) == len(sync_ends), "Mismatched sync starts/ends"

    for start, end in zip(sync_starts, sync_ends):
        assert (
            start.timestamp_ns <= end.timestamp_ns
        ), "Sync end timestamp is before sync start"
        assert start.thread_id == 2, "Boundary check should run on thread 2 (Macro)"
        assert end.thread_id == 2, "Boundary check should run on thread 2 (Macro)"

    # Verify state broker transitions
    for e in state_updates:
        assert (
            e.thread_id == 1
        ), "StateBroker updates should run on thread 1 (Micro Execution)"
